### PR TITLE
tests leak fix

### PR DESCRIPTION
**Pull request by JohnPJenkins**
Fixes leaks introduced by #112

### CODE REVIEW

**Comment by soumagne** [comment]
Hmm does not seem to be fixed: https://cdash.hdfgroup.org/viewDynamicAnalysis.php?buildid=20646

**Comment by soumagne** [comment]
Yeah the check only means that the configure/build/test were run sucessfully, you still need to look at the dashboard to check that test results are passing or not. I can probably make it more strict so that it actually fails every time a test does not pass.

**Comment by soumagne** [comment]
Just check the travis build number in the build name: travis-ci-linux-x64-gcc-debug-addresssanitizer-231

**Comment by soumagne** [comment]
My problem is that if I make it more strict, it will fail for everything, even for random failures like we currently have with the CCI tcp plugin... so I would rather keep it more permissive for now.

**Comment by soumagne** [comment]
I just tried on my laptop and I don't see the leaks anymore with tsan, I'm not sure why it shows up with travis still...

**Comment by soumagne** [comment]
Well we don't test sm on travis so that's normal. Also Cdash only collects the results that the travis build submits, it's not doing any test itself.

**Comment by soumagne** [comment]
I'm using 5.3.1 here and it's gone too for me. I suspect travis is not fetching the pull request correctly...

**Comment by soumagne** [comment]
Can you try to push a fake commit to that pull request to trigger the build again?

**Comment by soumagne** [comment]
Yes there were some failures, I forgot now the actual error though I would have to try again

**Comment by soumagne** [comment]
Hmm that's really bizarre, same failures again in the dashboard after your fake commit...

**Comment by soumagne** [comment]
Yes I tried those already, it's buggy, and same for that https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1413474

**Comment by soumagne** [comment]
I don't think it's a compiler issue... ok I have another idea :) can you try to push a commit that prints a line in the test so that we can see if we're testing the right version?

**Comment by soumagne** [comment]
Yes there is an issue with the na_simple_cci* tests, I saw that too, I haven't figured out yet why it fails, that's the only ones that fail.

**Comment by hyoklee** [comment]
Awesome, @JohnPJenkins!

**Comment by soumagne** [comment]
As I suspected, I don't see the string, so that means it's indeed not testing the right version... funny

**Comment by soumagne** [comment]
Maybe they just broke something in the travis code

**Comment by soumagne** [comment]
Could that be related to #111 ?

**Comment by soumagne** [comment]
`./src/plugins/ctp/sm/ctp_sm_api.c:1674:	node = tsearch(sconn, &sep->conns, sm_compare_conns);`

**Comment by soumagne** [comment]
We can pass options to Ctest using CTEST_MEMORYCHECK_SANITIZER_OPTIONS, see for example in Testing/script/travis_script.cmake line 88, so I think we could do that

**Comment by soumagne** [comment]
Well but that's another topic, I would like to understand first why travis is not testing the right revision in the pull requests...

**Comment by soumagne** [comment]
Here is what travis does:
```
0.60s$ git clone --depth=50 https://github.com/mercury-hpc/mercury.git mercury-hpc/mercury

Cloning into 'mercury-hpc/mercury'...

remote: Counting objects: 427, done.

remote: Compressing objects: 100% (280/280), done.

remote: Total 427 (delta 246), reused 247 (delta 144), pack-reused 0

Receiving objects: 100% (427/427), 270.00 KiB | 0 bytes/s, done.

Resolving deltas: 100% (246/246), done.

Checking connectivity... done.

$ cd mercury-hpc/mercury

0.30s$ git fetch origin +refs/pull/114/merge:

remote: Counting objects: 18, done.

remote: Compressing objects: 100% (17/17), done.

remote: Total 18 (delta 14), reused 4 (delta 1), pack-reused 0

Unpacking objects: 100% (18/18), done.

From https://github.com/mercury-hpc/mercury

 * branch            refs/pull/114/merge -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD
```

**Comment by soumagne** [comment]
OK! I'll post here if I find something. For now what I can say is that the git command is correct and gets your commit with the string but the string is not in log. You can get the log by clicking on raw log and look for the string which should appear just before the listen printf.

**Comment by soumagne** [comment]
osx fix in c98da537119d4732190e477de7fcfdb1558d235c and pull request ctest fix in 5f9aa818bf1e75bd53937ef8d5fd585b7f6aba49

**Comment by soumagne** [comment]
Yes I fixed the issue on OS X (segfault with locator in na_info_parse) and the pull request problem where ctest was actually doing a checkout of another revision so it's not doing that anymore. I haven't fixed the na_simple_* test though but that should be a separate issue.

**Comment by soumagne** [comment]
Oh and before we change topic and forget, let me know when you have a look at #107

**Comment by soumagne** [comment]
Oh no problem, just meant when you have time, that's really minor anyway, thanks!

**Comment by scottatchley** [comment]
Hi John,

I just pushed a commit to CCI that fixes several leaks in the SM connection path. Can you recheck the below or are you filtering out CCI internal leak messages?

Scott

**Comment by soumagne** [comment]
Yes it reports thread sanitizer and address sanitizer results. https://cdash.hdfgroup.org/index.php?project=MERCURY The interface should be updated and cleaner when we update to the latest version of cdash but the IT person has not gotten to it yet.

We are not filtering out CCI leak messages.

**Comment by soumagne** [comment]
Also travis does not test sm for now, I have to get back to it as they were some issues when I enabled it, I can try again though.

**Comment by scottatchley** [comment]
Thanks for the check!

Are there any outstanding issues with the sm transport? Blocking mode? Race conditions? Other?


________________________________

**Comment by carns** [comment]
Blocking mode on the cci/sm transport works great for me!  Not even a hiccup.

**Comment by scottatchley** [comment]
Ok, thanks for the confirmation. I will continue to focus on verbs. I will probably write a CCI native test that spawns multiple threads on both a client and server and repeatedly connect, communicate, disconnect, and repeat.

**Comment by soumagne** [comment]
@scottatchley , you might want to look at that: https://cdash.hdfgroup.org/viewDynamicAnalysisFile.php?id=46913
I enabled the sm transport in travis and am getting some errors.

**Comment by carns** [comment]
FYI, the RMA options specifically will fail when using CCI/SM on some linux distros if you don't set /proc/sys/kernel/yama/ptrace_scope to 0 (as root).  This loosens permission restrictions on that system call to allow two pids owned by the same users to access each other's memory.

If CCI/SM gets a predictable errno out of the cma system calls in this case then maybe it could print a verbose error message suggesting that fix?  A few of us have bumped into it at different times.

Not sure if that's what's going on, but it might be worth checking in that docker image.

**Comment by soumagne** [comment]
Hmm ok thanks I just checked and it's indeed set to 1 so I guess that's the problem. I can't change that value though as this image does not allow me to be root unless I use another image which requires other changes and increases the boot time.

**Comment by soumagne** [comment]
1 - restricted ptrace: a process must have a predefined relationship
    with the inferior it wants to call PTRACE_ATTACH on. By default,
    this relationship is that of only its descendants when the above
    classic criteria is also met. To change the relationship, an
    inferior can call prctl(PR_SET_PTRACER, debugger, ...) to declare
    an allowed debugger PID to call PTRACE_ATTACH on the inferior.
    Using PTRACE_TRACEME is unchanged.

I guess we could also call prctl in that case...

**Comment by scottatchley** [comment]
You beat me to this.

This is only required if using CMA. If using the mmap bounce buffers, it is not needed.

Perhaps we can add the prctl() call if CMA is enabled. I am hesitant to do that in a library without warning the application user that this security feature has been disabled.

Thoughts/comments?

**Comment by scottatchley** [comment]
I just reread the process_vm_[write|read]v() manpage. If it fails with EPERM, I have added the following message:

ctp_sm_rma: process_vm_[write|read]v() failed because it cannot trace another process. See https://www.kernel.org/doc/Documentation/security/Yama.txt for more details.

**Comment by soumagne** [comment]
Ah ok then for the time being I could just simply try to have CMA disabled on the travis images, I also understand now why only the tests that call NA_Put/NA_Get were failing.

Hmmm yes that's true, although that's probably not as worse as setting ptrace_scope to 0 as root... Just googled it to see if others had the same issue and found that discussion: https://www.open-mpi.org/community/lists/users/2015/02/26391.php ... looks like their decision was to enable CMA if no yama and no PR_SET_PTRACER.

Maybe the best solution is to keep the verbose error message or have an option force CMA I guess which would call prctl() and throw a warning...

**Comment by scottatchley** [comment]
CCI has --with-cma to enable CMA. Perhaps I should change the default to --without-cma and include a message in the configure --help output that enabling CMA will force the ability to trace? I could put more detail in the sm README.

**Comment by soumagne** [comment]
I added `prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0)` if sm is used in the mercury testing suite and everything is fine now with CMA.

Just been thinking a little more and if enabling CMA in CCI changes permissions under the hood then it may do too much in some cases if let's say somebody only wants to have CMA enabled between parent and child processes and not any process. I think the best option is to just keep the verbose error message and let the app decide :)

**Comment by carns** [comment]
For my 2c, I like the idea of keeping cma on by default and just doing what we can via docs/error messages to tell people how to either turn it off or set permissions.

I'm worried about the failure mode of accidentally compiling without CMA support and then being confused by the resulting performance :)

**Comment by scottatchley** [comment]
Ok, I will leave configure alone. If it detects CMA, it will compile it in. If compiled in and it fails, it will print the warning once when the first RMA fails with EPERM.

**Pull request closed without merging**
