### PR TITLE
Boost rollup

### LINKED ISSUE #211: ship with boost preprocessor headers
requiring boost inflates mercrury's dependencies (consider the case of creating a docker image).   If mercury shipped with and installed the boost preprocessor headers, we could skip the boost dependency and save hundreds of megabytes.  boost is also lengthy to compile, so being able to skip the boost dependency would speed up `spack install mercury`, too. 

The boost tool 'bcp' can package up the headers for it: for example

    bcp preprocessor --boost=/sandbox/robl/boost_1_66_0/ src/boost

### PR DESCRIPTION
**Pull request by roblatham00**
If we ship with the boost preprocessor headers we don't need to depend on boost and users can still get the fancy helper macros.    I'm pretty nervous about the cmake changes.  Also not entirely convinced yet that mercury clients will not notice this change...

Closes #211

### CODE REVIEW

**Comment by soumagne** [comment]
Thanks! Yeah I think something is missing in the cmake config but I can take care of it. Also I would still keep the conditional to check for boost so we probably don't need commit d4559dba98e1c791b189c0925b59fa994b928a6f

**Comment by roblatham00** [comment]
OK, i have remove the HAVE_BOOST checks, but I don't think I am correctly telling mercury "hey, use these headers"

**Comment by soumagne** [comment]
OK I will look at it

**Comment by soumagne** [comment]
OK I see what needs to be fixed. I'm working on it now.

**Comment by soumagne** [comment]
Merged in 662423e

**Pull request closed without merging**
