### PR TITLE
NA OFI: return appropriate error code if operation cannot be canceled

### PR DESCRIPTION
**Pull request by soumagne**
This is related to #284

### CODE REVIEW

**Comment by soumagne** [comment]
@yulujia could you please try that pull request out?

**Comment by yulujia** [comment]
@soumagne sure, let me try it.

**Comment by yulujia** [comment]
now I can get return code -HG_CANCEL_ERROR from HG_Cancel(). I should be able to work with this. thanks for the patch.

**Comment by yulujia** [comment]
Jerome, can you land this PR?

**Comment by soumagne** [comment]
Done

**Pull request merged**
