### PR TITLE
NA OFI: enable tcp provider using tcp;ofi_rxm and MR mode fixes

### PR DESCRIPTION
**Pull request by soumagne**
Currently does not pass bulk tests.

### CODE REVIEW

**Comment by ael-code** [comment]
3 days ago the new `1.7.1` libfabric version has been released. And the [changelog](https://github.com/ofiwg/libfabric/blob/v1.7.x/NEWS.md) shows a lot of improvement and fixes for both `TCP` and `RXM`.  Maybe the bulk-transfer tests will pass with this new version

**Comment by ael-code** [comment]
Any progress on this?

**Comment by soumagne** [comment]
Still on my queue to get back to it but should be relatively soon now. Is there anything that you can't currently do with the sockets provider?

**Comment by ael-code** [comment]
> Still on my queue to get back to it but should be relatively soon now. Is there anything that you can't currently do with the sockets provider?
Sockets provider is working flawlessly, it is just a matter of performance. We would like to move to the new TCP provider of libfabbric

**Comment by soumagne** [comment]
Still having the same issues with 1.8.0rc1

**Comment by soumagne** [comment]
Bulk requests fail with following error message:
```
libfabric:24412:tcp:ep_data:tcpx_validate_rx_rma_data():392<warn> invalid rma iov received
libfabric:24412:tcp:domain:tcpx_get_rx_entry_op_read_req():523<warn> invalid rma data
libfabric:24412:ofi_rxm:ep_ctrl:rxm_eq_readerr():88<warn> fi_eq_readerr: err: Invalid argument (22), prov_err: Success (0)
```

**Comment by soumagne** [comment]
Opened issue https://github.com/ofiwg/libfabric/issues/5102, that's the reason for RMA transfers failing. Still getting some weird completion event tags afterwards though so need to fix that too...

**Comment by soumagne** [comment]
@ael-code please give a try to the `topic_ofi_tcp` branch, it should be good to go now. Please let me know if you see any issues.

**Comment by soumagne** [comment]
Actually no you should probably wait, there are multi-threading issues reported by the thread sanitizer with lock order inversion issues. That will need to be fixed in libfabric as well it looks like... I'll open another issue tomorrow.

**Comment by soumagne** [comment]
Opened https://github.com/ofiwg/libfabric/issues/5104, should not prevent from using the tcp provider though.

**Comment by ael-code** [comment]
Let me know when I can test this and I'll give back some feedback.

**Comment by carns** [comment]
I just tried to test it with a margo example program, but the server isn't starting up.  Here is the output when I set FI_LOG_LEVEL=debug, just snipping the part that looks relevant to tcp:

```libfabric:15354:tcp:core:fi_param_define_():231<info> registered var iface
libfabric:15354:tcp:core:fi_param_define_():231<info> registered var port_low_range
libfabric:15354:tcp:core:fi_param_define_():231<info> registered var port_high_range
libfabric:15354:tcp:core:fi_param_get_():280<info> variable port_high_range=<not set>
libfabric:15354:tcp:core:fi_param_get_():280<info> variable port_low_range=<not set>
libfabric:15354:core:core:ofi_register_provider():374<info> registering provider: tcp (1.0)
libfabric:15354:core:core:ofi_register_provider():374<info> registering provider: ofi_perf_hook (1.0)
libfabric:15354:core:core:ofi_register_provider():374<info> registering provider: ofi_noop_hook (1.0)
libfabric:15354:ofi_rxm:core:fi_param_get_():280<info> variable use_srx=<not set>
libfabric:15354:tcp:core:fi_param_get_():280<info> variable iface=<not set>
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://192.168.1.24:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://172.17.0.1:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://172.18.0.1:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in6://[fe80::c3e6:eea:cff5:75aa]:0
libfabric:15354:tcp:core:ofi_insert_loopback_addr():1092<info> available addr: : fi_sockaddr_in://1.0.0.127:0
libfabric:15354:tcp:core:ofi_insert_loopback_addr():1104<info> available addr: : fi_sockaddr_in6://[::1]:0
libfabric:15354:core:core:ofi_layering_ok():794<info> Need core provider, skipping ofi_mrail
libfabric:15354:ofi_rxm:core:fi_param_get_():280<info> variable use_srx=<not set>
libfabric:15354:tcp:core:fi_param_get_():280<info> variable iface=<not set>
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://192.168.1.24:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://172.17.0.1:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://172.18.0.1:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in6://[fe80::c3e6:eea:cff5:75aa]:0
libfabric:15354:tcp:core:ofi_insert_loopback_addr():1092<info> available addr: : fi_sockaddr_in://1.0.0.127:0
libfabric:15354:tcp:core:ofi_insert_loopback_addr():1104<info> available addr: : fi_sockaddr_in6://[::1]:0
libfabric:15354:core:core:ofi_layering_ok():794<info> Need core provider, skipping ofi_mrail
libfabric:15354:tcp:core:fi_param_get_():280<info> variable iface=<not set>
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://192.168.1.24:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://172.17.0.1:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in://172.18.0.1:0
libfabric:15354:tcp:core:ofi_get_list_of_addr():1198<info> available addr: : fi_sockaddr_in6://[fe80::c3e6:eea:cff5:75aa]:0
libfabric:15354:tcp:core:ofi_insert_loopback_addr():1092<info> available addr: : fi_sockaddr_in://1.0.0.127:0
libfabric:15354:tcp:core:ofi_insert_loopback_addr():1104<info> available addr: : fi_sockaddr_in6://[::1]:0
libfabric:15354:core:core:ofi_layering_ok():794<info> Need core provider, skipping ofi_mrail
libfabric:15354:core:core:fi_fabric_():1084<info> Opened fabric: TCP-IP
libfabric:15354:core:core:fi_fabric_():1084<info> Opened fabric: TCP-IP
libfabric:15354:ofi_rxm:core:fi_param_get_():280<info> variable use_srx=<not set>
libfabric:15354:core:core:ofi_layering_ok():794<info> Need core provider, skipping ofi_mrail
libfabric:15354:core:core:fi_param_get_():280<info> variable universe_size=<not set>
libfabric:15354:ofi_rxm:av:util_av_init():455<info> AV size 1024
libfabric:15354:ofi_rxm:core:fi_param_get_():280<info> variable use_srx=<not set>
libfabric:15354:tcp:core:util_getinfo():157<info> FI_SOURCE set, but no node or service
libfabric:15354:core:core:fi_getinfo_():889<warn> fi_getinfo: provider tcp returned -22 (Invalid argument)
libfabric:15354:core:core:ofi_layering_ok():794<info> Need core provider, skipping ofi_mrail
libfabric:15354:core:core:fi_getinfo_():889<warn> fi_getinfo: provider ofi_rxm returned -61 (No data available)
# NA -- Error -- /home/pcarns/working/src/mochi/mercury/src/na/na_ofi.c:2023
 # na_ofi_endpoint_open(): fi_getinfo((null)) failed, rc: -61(No data available).
```

I'm using `"tcp;ofi_rxm://"` as the address string on the server.

Do you see anything obvious I'm doing wrong here?

**Comment by carns** [comment]
Oh, the server starts if I give it a fully specified address like `"ofi+tcp;ofi_rxm://127.0.0.1:3000"`.  Is this necessary?  It looks like I would maybe need to modify my client code to allow it to specify it's own address too.

**Comment by soumagne** [comment]
@ael-code yes please give it a try and let me know if you encounter any issues

**Comment by soumagne** [comment]
@carns with sockets before you could start the server without specifying anything?

**Comment by soumagne** [comment]
alright yes I see, we don't really do anything different in the OFI plugin so sounds like a provider issue

**Comment by carns** [comment]
Right, even in this branch I can start without a fully specified address using sockets:

```[pcarns@carns-x1 examples (master)]$ ./margo-example-server "sockets://"
# accepting RPCs on address "ofi+sockets://192.168.1.24:46265"
^C
```
But not with tcp:
```
[pcarns@carns-x1 examples (master)]$ ./margo-example-server "tcp;ofi_rxm://"
# NA -- Error -- /home/pcarns/working/src/mochi/mercury/src/na/na_ofi.c:2023
 # na_ofi_endpoint_open(): fi_getinfo((null)) failed, rc: -61(No data available).
# NA -- Error -- /home/pcarns/working/src/mochi/mercury/src/na/na_ofi.c:3282
 # na_ofi_initialize(): Could not create endpoint for (null)
# NA -- Error -- /home/pcarns/working/src/mochi/mercury/src/na/na.c:356
 # NA_Initialize_opt(): Could not initialize plugin
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury_core.c:1135
 # hg_core_init(): Could not initialize NA class
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury_core.c:3601
 # HG_Core_init_opt(): Cannot initialize HG core layer
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury.c:1092
 # HG_Init_opt(): Could not create HG core class
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury_core.c:3679
 # HG_Core_context_create_id(): NULL HG core class
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury.c:1188
 # HG_Context_create_id(): Could not create context for ID 0
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury_core.c:4452
 # HG_Core_create(): NULL HG core context
# HG -- Error -- /home/pcarns/working/src/mochi/mercury/src/mercury.c:1742
 # HG_Create(): Cannot create HG handle with ID 0
[mutex.c:120] ABT_mutex_free: 20
Error: margo_init()
```

**Comment by carns** [comment]
I have not looked in the libfabric code at all, but FWIW the tcp provider man page makes it sound as if it is supposed to be capable of creating it's own "passive" endpoints:

https://github.com/ofiwg/libfabric/blob/master/man/man7/fi_tcp.7#L58

(that part of the man page describes environment variables that set the bounds on port numbers it will select)

**Comment by ael-code** [comment]
As @carns already mentioned, it is not possible anymore to instantiate mercury by providing just the transport protocol prefix. Instead it is necessary to pass at least the hostname/ip/interface field, thus something like this `ofi+tcp;ofi_rxm` or `ofi+tcp;ofi_rxm://` won't work, while `ofi+tcp;ofi_rxm://localhost` or `ofi+tcp;ofi_rxm://127.0.0.1` works.

While on the server I always pass also the ip address I want Mercury to bind to, for the client I usually pass only the protocol string. This was working till now.

Moreover the lookup of addresses is not working for me, when I try to lookup server address I get the following:
```
[2019-07-11 11:35:28.223] [debug] Looking up address: 'ofi+tcp;ofi_rxm://127.0.0.1:43809'
# NA -- Error -- /opt/gkfs/deps_src/mercury/src/na/na_ofi.c:3636
 # na_ofi_addr_lookup(): Unrecognized provider type found from: 
# HG -- Error -- /opt/gkfs/deps_src/mercury/src/mercury_core.c:1403
 # hg_core_addr_lookup(): Could not start lookup for address 
# HG -- Error -- /opt/gkfs/deps_src/mercury/src/mercury_core.c:4290
 # HG_Core_addr_lookup(): Could not lookup address
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to lookup address: HG_NA_ERROR
```

**Comment by soumagne** [comment]
Yes I'm working on getting the initialization fixed. For your lookup error though that looks like an error on your initialization, can you make sure that you're using the same transport/protocol? You might have been using sockets thinking you were using tcp.

**Comment by soumagne** [comment]
Although in the error message that you get, the provider name seems to be blank so let me check that this is not some sort of bad interaction with the formatting of strings when using the SM routing option.

**Comment by ael-code** [comment]
> For your lookup error though that looks like an error on your initialization, can you make sure that you're using the same transport/protocol? You might have been using sockets thinking you were using tcp.

I'm sure I'm using the same transport/protocol on both sides

**Comment by ael-code** [comment]
> Although in the error message that you get, the provider name seems to be blank so let me check that this is not some sort of bad interaction with the formatting of strings when using the SM routing option.

I've compiled mercury with SM auto-routing option, but I've disable it at runtime.

**Comment by soumagne** [comment]
@ael-code yes that was related to the SM routing issue that you had entered before. I pushed the fix for it, try again now.

**Comment by soumagne** [comment]
@carns please try again, it should work fine now if you just pass ofi+tcp without any hostname

**Comment by ael-code** [comment]
I've tested the new version and I can confirm that the initialization and lookup now works as expected.

Unfortunately I've discovered another minor problem, If I run the new `ofi+tcp` transportation layer on top of an Omni-path device the very first `HG_forward` that is issued will never trigger its callback function. That is really strange since the server is actually responding correctly to that RPC.
If I run the same code on the standard TCP interface, everything works as expected.
The old `ofi+sockets` transportation layer was working both on TCP and Omni-path interface.

**Comment by carns** [comment]
I haven't done any extensive testing yet, but I can confirm that the tcp provider works correctly without a fully specified hostname now too.  Thanks @soumagne !  I also confirmed that I can switch back and forth between using the tcp and sockets provider in the same build by using `tcp://` or `sockets://`.

**Pull request merged**
