### PR TITLE
NA: multi-recv support and switch NA OFI to using non-tagged unexpected messages

### PR DESCRIPTION
**Pull request by soumagne**

### CODE REVIEW

**Comment by roblatham00** [comment]
I tested this on summit with the `mochi-quintain` program and immediately got a segfault starting the `bedrock` service:

```
(gdb) where
#0  0x0000200000f37c5c in rxm_ep_rma_common () from /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/libfabric-1.15.1-be2ejuogia7chog7yczwb26nyie6kzkl/lib/libfabric.so.1
#1  0x0000200000e6af68 in fi_writemsg (ep=<optimized out>, msg=<optimized out>, flags=<optimized out>)
    at /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/libfabric-1.15.1-be2ejuogia7chog7yczwb26nyie6kzkl/include/rdma/fi_rma.h:136
#2  0x0000200000e6b504 in na_ofi_rma_post (ep=<optimized out>, rma_info=rma_info@entry=0x3d205ef8, context=context@entry=0x3d206090)
    at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/na/na_ofi.c:4864
#3  0x0000200000e6f1a0 in na_ofi_rma_common (na_ofi_class=0x3d00ef00, context=<optimized out>, cb_type=cb_type@entry=NA_CB_PUT, callback=<optimized out>, arg=arg@entry=0x3d205d70,
    fi_rma_op=fi_rma_op@entry=0x200000e6af40 <fi_writemsg>, fi_rma_op_string=fi_rma_op_string@entry=0x200000e86418 "fi_writemsg", fi_rma_flags=fi_rma_flags@entry=268435456,
    na_ofi_mem_handle_local=<optimized out>, na_ofi_mem_handle_local@entry=0x3cf74480, local_offset=<optimized out>, na_ofi_mem_handle_remote=0x3cf74290, remote_offset=<optimized out>, remote_offset@entry=0,
    length=<optimized out>, length@entry=39, na_ofi_addr=na_ofi_addr@entry=0x3d02f9e0, remote_id=<optimized out>, remote_id@entry=0 '\000', na_ofi_op_id=na_ofi_op_id@entry=0x3d205ea0)
    at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/na/na_ofi.c:4816
#4  0x0000200000e6f824 in na_ofi_put (na_class=<optimized out>, context=<optimized out>, callback=<optimized out>, arg=0x3d205d70, local_mem_handle=0x3cf74480, local_offset=<optimized out>,
    remote_mem_handle=<optimized out>, remote_offset=0, length=39, remote_addr=0x3d02f9e0, remote_id=0 '\000', op_id=0x3d205ea0)
    at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/na/na_ofi.c:7104
#5  0x000020000048bdec in NA_Put (op_id=0x3d205ea0, remote_id=0 '\000', remote_addr=0x3d02f9e0, data_size=39, remote_offset=<optimized out>, remote_mem_handle=<optimized out>, local_offset=<optimized out>,
    local_mem_handle=<optimized out>, arg=<optimized out>, callback=<optimized out>, context=<optimized out>, na_class=<optimized out>)
    at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/na/na.h:1156
#6  hg_bulk_na_put (na_class=<optimized out>, context=<optimized out>, callback=<optimized out>, arg=<optimized out>, local_mem_handle=<optimized out>, local_offset=<optimized out>,
    remote_mem_handle=<optimized out>, remote_offset=<optimized out>, data_size=39, remote_addr=0x3d02f9e0, remote_id=0 '\000', op_id=0x3d205ea0)
    at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/mercury_bulk.c:471
#7  0x000020000048d9e8 in hg_bulk_transfer_na (hg_bulk_op_id=0x3d205d70, size=39, local_offset=0, local_flags=1 '\001', local_mem_handles=0x3d323a60, local_count=<optimized out>,
    local_segments=<optimized out>, origin_offset=0, origin_flags=130 '\202', origin_mem_handles=0x3cf623d0, origin_count=<optimized out>, origin_segments=<optimized out>, origin_id=0 '\000',
    na_origin_addr=0x3d02f9e0, op=HG_BULK_PUSH) at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/mercury_bulk.c:2143
#8  hg_bulk_transfer (core_context=<optimized out>, callback=<optimized out>, arg=<optimized out>, op=<optimized out>, origin_addr=<optimized out>, origin_id=origin_id@entry=0 '\000',
    hg_bulk_origin=<optimized out>, origin_offset=0, hg_bulk_local=<optimized out>, local_offset=<optimized out>, local_offset@entry=0, size=<optimized out>, size@entry=39, op_id=<optimized out>,
    op_id@entry=0x1) at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/mercury_bulk.c:1981
#9  0x000020000049198c in HG_Bulk_transfer (context=<optimized out>, callback=<optimized out>, arg=<optimized out>, op=<optimized out>, origin_addr=<optimized out>, origin_handle=<optimized out>,
    origin_offset=<optimized out>, local_handle=<optimized out>, local_offset=0, size=39, op_id=0x1)
    at /tmp/robl/spack-stage/spack-stage-mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/spack-src/src/mercury_bulk.c:2755
#10 0x000020000043d0f4 in margo_bulk_itransfer_internal (req=0x20000b7dfda0, size=39, local_offset=0, local_handle=0x3d323990, origin_offset=0, origin_handle=0x3cf62300, origin_addr=0x3d009aa0,
    op=HG_BULK_PUSH, mid=0x3d2c4010) at src/margo-core.c:1376
#11 margo_bulk_transfer (mid=0x3d2c4010, op=<optimized out>, origin_addr=0x3d009aa0, origin_handle=0x3cf62300, origin_offset=0, local_handle=0x3d323990, local_offset=0, size=39) at src/margo-core.c:1393
#12 0x00002000003f27c0 in ssg_group_refresh_recv_ult (handle=0x3cf7d960) at src/ssg-rpc.c:769
#13 _wrapper_for_ssg_group_refresh_recv_ult (handle=0x3cf7d960) at src/ssg-rpc.c:794
#14 0x00002000004fcda0 in ABTD_ythread_func_wrapper () from /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/argobots-main-n4hzycs2l22ebjwj2iha2w5bdat66b2e/lib/libabt.so.1
#15 0x0000200000507138 in ABTD_ythread_context_func_wrapper ()
   from /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/argobots-main-n4hzycs2l22ebjwj2iha2w5bdat66b2e/lib/libabt.so.1
#16 0x00002000004fd508 in init_and_switch_fcontext () from /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/argobots-main-n4hzycs2l22ebjwj2iha2w5bdat66b2e/lib/libabt.so.1
```

Pretty sure this segfault is related to the multi-receive, as I was running bedrock services 

Building mercury with this line added to our spack package.py
version('2.2.0-multi_recv', git='https://github.com/soumagne/mercury.git', branch='multi_recv', preferred=False)

To double check, I tried against mercury-2.2.0 and it behaves as expected.

**Comment by soumagne** [comment]
weird ok thanks for the heads-up. multi-recv should not affect bulk in any way but it's also possible that I messed something up, I will double check.

**Comment by roblatham00** [comment]
Still on summit:  you don't need to spin up bedrock to verify this.  You can use the `margo-p2p-bw` or `margo-p2p-latency` tests .   I didn't get a core file but I did get a big backtrace and signal 11:

```
[a01n18:3191987] *** Process received signal ***
[a01n18:3191987] Signal: Segmentation fault (11)
[a01n18:3191987] Signal code: Address not mapped (1)
[a01n18:3191987] Failing at address: 0x34
[a01n18:3191987] [ 0] linux-vdso64.so.1(__kernel_sigtramp_rt64+0x0)[0x2000000504d8]
[a01n18:3191987] [ 1] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/libfabric-1.15.1-be2ejuogia7chog7yczwb26nyie6kzkl/lib/libfabric.so.1(+0x87c5c)[0x200000cb7c5c]
[a01n18:3191987] [ 2] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/lib/libna.so.4(+0xaf68)[0x200000beaf68]
[a01n18:3191987] [ 3] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/lib/libna.so.4(+0xb504)[0x200000beb504]
[a01n18:3191987] [ 4] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/lib/libna.so.4(+0xf1a0)[0x200000bef1a0]
[a01n18:3191987] [ 5] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/lib/libna.so.4(+0xf824)[0x200000bef824]
[a01n18:3191987] [ 6] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/lib/libmercury.so.2(+0xbdec)[0x20000020bdec]
[a01n18:3191987] [ 7] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/lib/libmercury.so.2(+0xd9e8)[0x20000020d9e8]
[a01n18:3191987] [ 8] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mercury-2.2.0-multi_recv-fhmmuoy6ws567wceindam6i3hfulaztv/lib/libmercury.so.2(HG_Bulk_transfer+0xbc)[0x20000021198c]
[a01n18:3191987] [ 9] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mochi-margo-0.10-guiofwwzs3h7helg5x2tbqy7zlhqm2us/lib/libmargo.so.0(margo_bulk_transfer+0xe4)[0x20000015d0f4]
[a01n18:3191987] [10] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/mochi-ssg-0.5.3-jxw6yf2mwr3po4barw6n6d2bfll3r6li/lib/libssg.so.0(_wrapper_for_ssg_group_refresh_recv_ult+0x440)[0x2000001127c0]
[a01n18:3191987] [11] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/argobots-main-n4hzycs2l22ebjwj2iha2w5bdat66b2e/lib/libabt.so.1(+0x2cda0)[0x20000027cda0]
[a01n18:3191987] [12] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/argobots-main-n4hzycs2l22ebjwj2iha2w5bdat66b2e/lib/libabt.so.1(+0x37138)[0x200000287138]
[a01n18:3191987] [13] /autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-11.1.0/argobots-main-n4hzycs2l22ebjwj2iha2w5bdat66b2e/lib/libabt.so.1(init_and_jump_fcontext+0x0)[0x20000027d508]
```

this is a test that runs fine in our nightly tests on x86 (cooley)

**Comment by soumagne** [comment]
Thanks I will have a look.

**Comment by roblatham00** [comment]
I was wrong in my last post.  we do /not/ test multi-recive in our nightly tests on cooley.   Cooly (x86) segfaults with multi-recieve too, so it's not a ppc vs x86 thing.    In chat, Phil wondered if perhaps libfabric 1.16.1 fixes anything:  I tried again with libfabric-1.16.1 but that also triggered a segfault.  similar backtraces
```
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/libfabric-1.16.1-slijutv5vdeefr7denbtmtkb3p4ilaj2/lib/libfabric.so.1(+0x64154)[0x7f5e274e9154]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/libfabric-1.16.1-slijutv5vdeefr7denbtmtkb3p4ilaj2/lib/libfabric.so.1(+0x64332)[0x7f5e274e9332]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/mercury-develop-multi_recv-34vyd4pmgjxl7rrzulbygsctrbhp23by/lib/libna.so.4(+0x82f5)[0x7f5e2773e2f5]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/mercury-develop-multi_recv-34vyd4pmgjxl7rrzulbygsctrbhp23by/lib/libna.so.4(+0xd0b9)[0x7f5e277430b9]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/mercury-develop-multi_recv-34vyd4pmgjxl7rrzulbygsctrbhp23by/lib/libna.so.4(+0xd59a)[0x7f5e2774359a]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/mercury-develop-multi_recv-34vyd4pmgjxl7rrzulbygsctrbhp23by/lib/libmercury.so.2(+0xb717)[0x7f5e28829717]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/mercury-develop-multi_recv-34vyd4pmgjxl7rrzulbygsctrbhp23by/lib/libmercury.so.2(HG_Bulk_transfer+0xa2)[0x7f5e2882b892]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/mochi-margo-0.10-s62uqtbnlpbhhwjpd65qhirkqhwtxavf/lib/libmargo.so.0(margo_bulk_transfer+0x9e)[0x7f5e28c6f8ee]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/mochi-ssg-0.5.3-dbxhw2tjjil2yfxj2rbpj7lyfleg643i/lib/libssg.so.0(_wrapper_for_ssg_group_refresh_recv_ult+0x357)[0x7f5e28e958c7]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/argobots-1.1-joalawb6eftxjugxps5elczpybsa2u6n/lib/libabt.so.1(+0x17b7a)[0x7f5e2860db7a]
/home/robl/src/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/argobots-1.1-joalawb6eftxjugxps5elczpybsa2u6n/lib/libabt.so.1(+0x17d01)[0x7f5e2860dd01]
```

**Comment by soumagne** [comment]
ok well also right now even with that branch, multi-recv is not being used unless you explicitly request it through `HG_Init_opt()` so I would not expect that's the issue. Do you see that issue only with verbs or also with tcp ? (sorry haven't tried the margo test yet but hopefully today)

**Comment by roblatham00** [comment]
so far have only seen with verbs, not with tcp -- segfaulting test no longer segfaults with "tcp"

**Comment by soumagne** [comment]
@roblatham00 sorry for the delay in getting to that segfault, there were a bunch of other things that needed to be cleaned up in that branch. Feel free to try it again with verbs, everything should be fixed. Just note that now, multi-recv will be enabled by default when supported. If for any reason you'd want to disable it, you'd have to set `no_multi_recv` to 1 as part of the HG init options.

**Comment by roblatham00** [comment]
Thanks the new branch works well on Summit now.   I collected some "mochi-quintain" data -- without a progress thread there's no change in latency.  With a progress thread and dedicated argobots pools there is a big reduction in the long tail latency times.  

image

This is with one provider on one summit node, 32 client nodes each with 42 threads.

**Comment by soumagne** [comment]
oh ok nice, that's interesting, just a supposition but sounds like the high latency could have been caused by the overhead of having some messages arriving before we had a buffer pre-posted for them? i.e. treated as unexpected by the underlying provider and then memcpied into our buffer. Or it could have also been caused by the fact of having too many recvs posted.... just the two things I can think of right now to explain the difference.

**Pull request merged**
