### PR TITLE
fix uninitialized variable

### PR DESCRIPTION
**Pull request by carns**

### CODE REVIEW

**Comment by soumagne** [comment]
Ah I see thanks I'll just do a memset instead to make sure the struct is initialized

**Comment by carns** [comment]
Ok, sounds good.  I found this while trying to track down a problem in a different WIP merge request; once you have a memset fix in master I'll rebase that branch.

**Comment by soumagne** [comment]
It's in master now

**Comment by carns** [comment]
thanks Jerome!

**Pull request closed without merging**
