### PR TITLE
HG Bulk: add support for memory attributes w/ HG_Bulk_create_attr()

### PR DESCRIPTION
**Pull request by soumagne**
Support CUDA, ROCm, ZE

NA: add support for memory types on registration

NA OFI: update to support OFI memory types

NA UCX: update to support UCX memory types

### CODE REVIEW

**Comment by carns** [comment]
Hi @soumagne , can you either add a #define feature I can check for in the Mercury headers (e.g. HG_HAS_BULK_CREATE_ATTR) or bump the API version number in this PR? 

I was working on margo bindings for this new function to be enabled or disabled conditionally depending on whether the function is present in Mercury.  I have an autoconf test for the function right now, but I realized it won't quite work cleanly because I need to toggle the function definition in margo.h to account for the `struct hg_bulk_attr` type which may not be defined.

**Comment by carns** [comment]
(follow up after offline discussion); this PR does not have a version number bump, but I'll assume that there will be one when this PR lands.  I'll do a matching WIP PR on margo that checks the version number, and adjust it later if the version number is different than expected when it's time to add support.

**Comment by soumagne** [comment]
Something worth mentioning also is that currently if we use the GPU registration, the eager bulk code path will be disabled automatically. Ideally maybe it would be nice to be able to do something like a cudaMemcpy or GDRCopy and then embed that into a small eager message but we don't have the code to do that right now. Libfabric does support it though so maybe we could force a "local" put or get into the eager buffer to trigger that code path in libfabric, I'll need to take a closer look and see if it's worth doing it as opposed to just let the RMA happen on the remote node.

**Comment by Zhang690683220** [comment]
A interesting finding with the current implementation is that:
1. when I do a cuda memory -> remote host memory HG_bulk_transfer(), it works with any bulk data size ( as long as it <=1GB)
2. But when I do a remote host memory -> cuda memory HG_bulk_transfer(), it will report a error 12 (HG_PROTOCOL_ERROR) when the data size is >= 1MB with the following msg:
mlx5: c001-007.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00008813 08014857 000ac2d2
ERROR: (get_rpc): margo_bulk_transfer() failure (12)
mlx5: c001-007.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00008813 08014854 000aedd2
ERROR: (get_rpc): margo_bulk_transfer() failure (12)
mlx5: c001-007.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00008813 08014855 000aecd2
mlx5: c001-007.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00008813 08014856 000aefd2

**Comment by soumagne** [comment]
@Zhang690683220 what do you pass as memory type? Could you please turn on debug info using `HG_LOG_LEVEL=warning` and `HG_LOG_SUBSYS=na`

**Comment by Zhang690683220** [comment]
After starting to use the `HG_Bulk_create_attr()`, I even got some error from sending a GPU data to remote CPU, which works for previous  `HG_Bulk_create()`.

The debug settings are `HG_LOG_LEVEL=warning`, `HG_LOG_SUBSYS=hg`. Then I got this:
```
# [2030782.027030] mercury->addr: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/na/na_ofi.c:1613
 # na_ofi_addr_ht_lookup(): fi_av_insert() failed, rc: 0 (Success)
# [2030782.027042] mercury->addr: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/na/na_ofi.c:3424
 # na_ofi_cq_process_recv_unexpected_event(): na_ofi_addr_ht_lookup() failed
# [2030782.027045] mercury->msg: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/na/na_ofi.c:3357
 # na_ofi_cq_process_event(): Could not process unexpected recv event
# [2030782.027050] mercury->hg: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/mercury_core.c:3871
 # hg_core_progress_na(): Could not make progress on NA (NA_PROTOCOL_ERROR)
# [2030782.027053] mercury->hg: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/mercury_core.c:3810
 # hg_core_poll(): hg_core_progress_na() failed
# [2030782.027056] mercury->hg: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/mercury_core.c:3666
 # hg_core_progress(): Could not make non-blocking progress on context
# [2030782.027058] mercury->hg: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/mercury_core.c:5031
 # HG_Core_progress(): Could not make progress
# [2030782.027061] mercury->hg: [error] /work/07555/bz186/longhorn/mercury-2.1.0/src/mercury.c:2024
 # HG_Progress(): Could not make progress on context (HG_PROTOCOL_ERROR)
[critical] unexpected return code (12: HG_PROTOCOL_ERROR) from HG_Progress()
dspaces_server: src/margo-core.c:1489: __margo_hg_progress_fn: Assertion `0' failed.
[c001-008:03900] *** Process received signal ***
[c001-008:03900] Signal: Aborted (6)
[c001-008:03900] Signal code:  (-6)
[c001-008:03900] [ 0] [0x2000000504d8]
[c001-008:03900] [ 1] /lib64/libc.so.6(abort+0x2b4)[0x2000018c1f94]
[c001-008:03900] [ 2] /lib64/libc.so.6(+0x355d4)[0x2000018b55d4]
[c001-008:03900] [ 3] /lib64/libc.so.6(__assert_fail+0x64)[0x2000018b56c4]
[c001-008:03900] [ 4] /work/07555/bz186/longhorn/apps/gcc-7.3.0/mochi-margo-0.9.7/lib/libmargo.so.0(__margo_hg_progress_fn+0x790)[0x200001373864]
[c001-008:03900] [ 5] /work/07555/bz186/longhorn/apps/gcc-7.3.0/argobots-1.1/lib/libabt.so.1(+0x2b940)[0x20000151b940]
[c001-008:03900] [ 6] /work/07555/bz186/longhorn/apps/gcc-7.3.0/argobots-1.1/lib/libabt.so.1(+0x2c684)[0x20000151c684]
[c001-008:03900] *** End of error message ***
```

**Comment by soumagne** [comment]
Hmm looks like you're using an old version, can you please try to use the master branch and apply the patch on top of that?

**Comment by soumagne** [comment]
I'm actually not even sure why you would get an error in that code path since it's not related to GPU...

**Comment by Zhang690683220** [comment]
Hi @soumagne , you are right. I mixed different versions of mercury. After fixing it, I still got the `NA_PROTOCOL_ERROR` from the `HG_Bulk_create_attr()`:
```
# [2035637.957957] mercury->hg: [warning] /work/07555/bz186/longhorn/mercury/src/mercury_core.c:3245
 # hg_core_send_output_cb(): Received NA_CANCELED event on handle that was not canceled
# [2035637.958064] mercury->hg: [warning] /work/07555/bz186/longhorn/mercury/src/mercury_core.c:3245
 # hg_core_send_output_cb(): Received NA_CANCELED event on handle that was not canceled
# [2035637.958150] mercury->hg: [warning] /work/07555/bz186/longhorn/mercury/src/mercury_core.c:3245
 # hg_core_send_output_cb(): Received NA_CANCELED event on handle that was not canceled
mlx5: c001-008.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000001 00000000 00000000 00000000
00000000 00008813 08000be3 000ad1d2
# [2035637.957883] mercury->hg: [error] /work/07555/bz186/longhorn/mercury/src/mercury_bulk.c:2395
 # hg_bulk_transfer_cb(): NA callback returned error (NA_PROTOCOL_ERROR)
ERROR: (get_rpc): margo_bulk_transfer() failure (12)
mlx5: c001-008.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000002 00000000 00000000 00000000
00000000 00008813 08000be4 000ad4d2
# [2035637.957943] mercury->hg: [error] /work/07555/bz186/longhorn/mercury/src/mercury_bulk.c:2395
 # hg_bulk_transfer_cb(): NA callback returned error (NA_PROTOCOL_ERROR)
ERROR: (get_rpc): margo_bulk_transfer() failure (12)
mlx5: c001-008.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00008813 08000be2 000ad2d2
# [2035637.958029] mercury->hg: [error] /work/07555/bz186/longhorn/mercury/src/mercury_bulk.c:2395
 # hg_bulk_transfer_cb(): NA callback returned error (NA_PROTOCOL_ERROR)
ERROR: (get_rpc): margo_bulk_transfer() failure (12)
mlx5: c001-008.longhorn.tacc.utexas.edu: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000003 00000000 00000000 00000000
00000000 00008813 08000be5 000acbd2
# [2035637.958127] mercury->hg: [error] /work/07555/bz186/longhorn/mercury/src/mercury_bulk.c:2395
 # hg_bulk_transfer_cb(): NA callback returned error (NA_PROTOCOL_ERROR)
ERROR: (get_rpc): margo_bulk_transfer() failure (12)
```
A finding that might be useful is: this only happens with iterative runs. If I set the total timestep in my code to 1, then everything goes fine. If it comes to >= 2, then this happens. I suspect it might have some bugs after the initial calls. It might narrow the location of the bug.

**Comment by soumagne** [comment]
Hmm that seems weird, would you be able to point me to your program so that I can try to reproduce it ?

**Comment by Zhang690683220** [comment]
Yes, of course. The binaries are in [dspaces_gpu_test](https://github.com/Zhang690683220/dspaces_gpu_test). The issue happens in  They are built on top of [dspaces](https://github.com/Zhang690683220/dspaces/tree/gpu-bulk). The dspaces is built on margo, so I added:
```
hg_return_t margo_bulk_create_attr(margo_instance_id    mid,
                                   hg_uint32_t          count,
                                   void**               buf_ptrs,
                                   const hg_size_t*     buf_sizes,
                                   hg_uint8_t           flags,
                                   struct hg_bulk_attr* attrs,
                                   hg_bulk_t*           handle)
{
    hg_return_t hret;
    double      tm1, tm2;
    int         diag_enabled = mid->diag_enabled;

    if (diag_enabled) tm1 = ABT_get_wtime();
    hret = HG_Bulk_create_attr(mid->hg_class, count, buf_ptrs, buf_sizes,
                               flags, attrs, handle);
    if (diag_enabled) {
        tm2 = ABT_get_wtime();
        __DIAG_UPDATE(mid->diag_bulk_create_elapsed, (tm2 - tm1));
    }

    return (hret);
}
```
to the margo-0.9.7.
The issue happens in [include/cuda_get.cuh](https://github.com/Zhang690683220/dspaces_gpu_test/blob/master/include/cuda_get.cuh#L104), which will call [dspaces_cuda_get()](https://github.com/Zhang690683220/dspaces/blob/gpu-bulk/src/dspaces-client.c#L2510), then goes to the [HG_Bulk_create_attr()](https://github.com/Zhang690683220/dspaces/blob/gpu-bulk/src/dspaces-client.c#L2140).

To run the test, you have to enable test when building dspaces with cmake, then you can get the `dspaces_server` in the `$install/bin/`. Copy the `dspaces_server` to the `cuda_put` and `cuda_get` dir. Configure the server with:
```
echo "## Config file for DataSpaces
ndim = 3
dims = 128, 128, 128
max_versions = 10
hash_version = 2
num_apps = 2
" > dataspaces.conf
```
Then do a `mpirun -n 1 ./dspaces_server verbs` in one terminal.
Do `mpirun -n 4 ./cuda_put --dims 3 --np 1 2 2 --sp 128 64 64 --ts 5` in a new terminal.
After the put, do `export DSPACES_CUDA_GET_MODE=2`, then `mpirun -n 4 ./cuda_get --dims 3 --np 1 2 2 --sp 128 64 64 --ts 5`, then you can find the errors at the server side.

**Comment by soumagne** [comment]
Hmm I don't see anything wrong I think but I see that you're allocating stuff on cuda everytime you enter that routine. Could you try to set `FI_MR_CUDA_CACHE_MONITOR_ENABLED=1`? and re-run your program?

**Comment by Zhang690683220** [comment]
Hi @soumagne, with the latest commit, my code works! So what is the cause?

**Comment by soumagne** [comment]
Ah ok excellent, I had just missed an OFI setting that was also required for selecting the right domain and turning on device registration support.

**Comment by Zhang690683220** [comment]
Nice! When can I expect this to be merged into the main branch?

**Comment by soumagne** [comment]
probably later today or tomorrow

**Comment by soumagne** [comment]
thanks again for your help on testing that!

**Comment by Zhang690683220** [comment]
Cool! Thank you very much!

**Pull request merged**
